services:
  # Backend API Service
  - type: web
    name: booking-bot-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: GOOGLE_CALENDAR_ID
        sync: false
      - key: PORT
        value: 8000

  # Frontend Streamlit Service
  - type: web
    name: booking-bot-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd frontend && streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BACKEND_URL
        value: https://booking-bot-backend.onrender.com
      - key: PORT
        value: 8501